<div style="margin: 5px 0px 5px 0px; background-color:#000000; width:99%; height:2px; float: left;">
	<div style="background-color: #FFFFFF; height: 100%; width:30px; float: left;">&nbsp;</div>
</div>
<div style='width: 99%;'>
<div style='text-align: left;'>
<p class="footer" style='clear:both;'>All Rights Reserved 2011. ComplaintsBBB (R) is a Registered Trademark of Global Enterprise Management Solutions. </p>
</div>
<div style='text-align: right;'>[ <a href='privacy.php'>Privacy Policy</a> ] [ <a href='tos.php'>Terms of Usage</a> ] [ <a href='sitemap.php'>Site Map</a> ]</div>
</div>
</div>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-25845909-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>
