<?php 
$complaint = array();
$complaint['title'] = 'Terms of Service';
$complaint['keywords'] = 'Consumer, Complaints, Services, Products, Terms';
$complaint['description'] = 'Terms of Service of Consumer Complaints Business Bulletin Board. Please be sure to read and make your self familier with the terms of services.';
include_once('header.inc'); 

?>
<div class="body" id='complaintsearch' style="width:550px; float:left">
<h3 class='subhead' style="width: 480px;">Terms of Service</h3>
<p style="text-align:justify">By accessing this web site, you are agreeing to be bound by these
  web site Terms and Conditions of Use, all applicable laws and regulations,
  and agree that you are responsible for compliance with any applicable local
  laws. If you do not agree with any of these terms, you are prohibited from
  using or accessing this site. The materials contained in this web site are
  protected by applicable copyright and trade mark law.</p>
<h3 class='subhead' style="width: 480px;">Use License</h3>
<p style="text-align:justify">Permission is granted to temporarily download one copy of the materials
  (information or software) on Consumer Awareness Inc’s web site for personal,
  non-commercial transitory viewing only. This is the grant of a license,
  not a transfer of title, and under this license you may not:
  modify or copy the materials;
  use the materials for any commercial purpose, or for any public display (commercial or non-commercial);
  attempt to decompile or reverse engineer any software contained on Consumer Awareness Inc’s web site;
  remove any copyright or other proprietary notations from the materials; or
  transfer the materials to another person or “mirror” the materials on any other server.
  This license shall automatically terminate if you violate any of these restrictions and may be terminated by Consumer Awareness Inc at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
<h3 class='subhead' style="width: 480px;">Disclaimer</h3>
<p style="text-align:justify">The materials on Consumer Awareness Inc’s web site are provided “as is”. Consumer Awareness Inc makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Consumer Awareness Inc does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
 <h3 class='subhead' style="width: 480px;">Limitations</h3>
<p style="text-align:justify">In no event shall Consumer Awareness Inc or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on Consumer Awareness Inc’s Internet site, even if Consumer Awareness Inc or a Consumer Awareness Inc authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.</p>
<h3 class='subhead' style="width: 480px;">Revisions and Errata</h3>
<p style="text-align:justify">The materials appearing on Consumer Awareness Inc’s web site could include technical, typographical, or photographic errors. Consumer Awareness Inc does not warrant that any of the materials on its web site are accurate, complete, or current. Consumer Awareness Inc may make changes to the materials contained on its web site at any time without notice. Consumer Awareness Inc does not, however, make any commitment to update the materials.</p>
<h3 class='subhead' style="width: 480px;">Links</h3>
<p style="text-align:justify">Consumer Awareness Inc has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Consumer Awareness Inc of the site. Use of any such linked web site is at the user’s own risk.</p>
<h3 class='subhead' style="width: 480px;">Site Terms of Use Modifications</h3>
<p style="text-align:justify">Consumer Awareness Inc may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.</p>
<h3 class='subhead' style="width: 480px;">Governing Law</h3>
<p style="text-align:justify">Any claim relating to Consumer Awareness Inc’s web site shall be governed by the laws of the State of California without regard to its conflict of law provisions.</p>
<p>General Terms and Conditions applicable to Use of a Web Site.</p>
<p>WE (CBBB) ARE A NOT FOR PROFIT COMMUNITY SERVICE WHO’S MISSION IS TO ADVOCATE CONSUMERS AND HELP BUSINESSES TO AVOID FRAUDULENT CLAIMS. WE DO NOT CHARGE A FEE FOR THE USE OF THIS SERVICE AND WE ARE NOT LIABLE FOR ANY LOSSES OR GAINS BY USING THIS SERVICE. OUR GOAL IS  TO PROVIDE A FULLY INTERACTIVE RESEARCH AND COMMUNICATION TOOL TO RESOLVE YOUR COMPLAINTS WITH BUSINESSES.</p>
<p>The Service is offered to you conditioned on your acceptance without modification of the terms, conditions, and notices contained herein.</p>
<p>ComplaintsBBB.com is a free site for all visitors, including consumers and businesses. ComplaintsBBB.com does not censor posted consumer messages, or business replies, or investigate them for accuracy.</p>
<p>Posted messages may be indexed by Internet search engines.</p>
<p>You may or may not receive e-mail messages from others (other consumers, businesses, etc.) due to posting your message on ComplaintsBBB.com.</p>
<p>As a user of ComplaintsBBB.com, you acknowledge that ComplaintsBBB.com does not prescreen or edit posted messages. You alone are responsible for the content of your messages, and the consequences of any such messages.</p>
<p>When messages have been posted to ComplaintsBBB.com they are made available for public view, and made available for indexing and reproduction by third-party search engines and directories. ComplaintsBBB.com has no control over the content taken from ComplaintsBBB.com by third-party sites. An individual who filed a complaint may withdraw it anytime by using the complaint management tool available on site.</p>
<p>ComplaintsBBB.com is not responsible for the validity of the consumer message complaints posted to the ComplaintsBBB.com site.</p>
<p>ComplaintsBBB.com in not responsible, in any way, for providing, or helping to provide, businesses’ responses to the consumer complaints that are posted on the ComplaintsBBB.com site, and /or forwarded to businesses. A complaint is only forwarded, via e-mail, to the e-mail address provided by the message author on the posting form, and when the checkbox “Notify business of complaint posting” is checked.</p>
<p>ComplaintsBBB.com does not knowingly allow incorrect or factually incorrect information to remain posted, as determined only by a U.S. court decision or opinion. If ComplaintsBBB.com is instructed to remove and delete a posted message by a U.S. court, then the message will be removed and deleted.</p>
<p>Many complaints posted to ComplaintsBBB.com are an historical ‘snapshot’ of an ongoing situation, as seen through the eyes and perception of an individual consumer, often with incomplete or inaccurate information at their disposal.</p>
<p>ComplaintsBBB.com always assumes that the consumer has a positive intent in writing their message, in helping themselves, in helping other consumers, in helping the subject business provide a better product or service.</p>
<p>Posted message consumer complaints and corresponding posted business replies both represent ‘snapshots in time’ of descriptions of a consumer experience, from the point of view of both consumers and businesses.</p>
<p>Due to the passage of time, or other factors, posted messages may be inaccurate or incomplete or the current status of the consumer situation may be different than the situation (s) described in the posted message. Posted messages don’t ‘expire.’ Posted messages are historical, dated messages (via URL) that may be updated, edited or removed by the message author.</p>
<p>A complaint message is assumed by ComplaintsBBB.com to be a description of a situation experienced by a consumer. A complaint is only a personal opinion by a consumer; a perception of a consumer. That personal perception and / or opinion based on their own personal experience, can be powerful, or meaningless, in the opinion of ComplaintsBBB.com, depending upon the context and content of what is written. And how that information is interpreted by whomever reads it. Which of course varies from person to person, depending on who they are, their own personal experiences, biases, opinions., Etc.</p>
<p>No conclusions are drawn by ComplaintsBBB.com, as to content validity. ComplaintsBBB.com does not edit or censor posted messages or investigate them for accuracy. ComplaintsBBB.com is a free Internet message board for the entire world to use.</p>
<p>Posted messages should describe a personal, firsthand experience. If a person experienced something personally, that person owns that information about their perception of, and opinion about, that personal experience, and is free to discuss their opinion about that experience, as a human, citizen, and legal entity, unless previously, already contractually bound otherwise.</p>
<p>It is the responsibility of a message author to make sure they are not contractually bound otherwise. It is the responsibility of this message author to determine on their own if they are not allowed to discuss the subject of their complaint, if this is the case, prior to posting a message to ComplaintsBBB.com.</p>
<p>If this ComplaintsBBB.com site user is contractually bound not to discuss a subject, that message author takes it upon their own risk if they post a message to ComplaintsBBB.com about that subject, because that message will be posted on ComplaintsBBB.com for public view.</p>
<p>ComplaintsBBB.com is only one free resource, among hundreds, even thousands, available to consumers and businesses, on the Internet, in print, etc. ComplaintsBBB.com is intended to help consumers make better purchase decisions, and help businesses serve consumers with better products and services. These are our guiding principles. However, ComplaintsBBB.com makes no promises.</p>
<p>Actual results from using ComplaintsBBB.com may be constructive or helpful. Or, actual results from using ComplaintsBBB.com may be destructive and harmful.</p>
<p>Visitors to ComplaintsBBB.com are free to form their own conclusions about any posted messages or content or information on our site, which is intended to be a place – and is indeed an Internet message board – for consumers and businesses to exchange information about products and services, hopefully in a constructive and meaningful way.</p>
<p>Each consumer message (consumer complaint) receives its own, dedicated Web page at ComplaintsBBB.com. A business reply is posted on the same Web page as the related consumer message.</p>
<p>Consumer messages and business replies and comments related to those messages are grouped together on the same single Web page. Content (consumer complaints / consumer messages / business replies) posted to ComplaintsBBB.com are only one single resource for consumers, for consumer to help draw their own conclusions, or not, about products and services.</p>
<p>ComplaintsBBB.com has no intention or agenda but to remain impartial and independent, and simply provide a free, public Internet message board platform to foster and support communications between consumers and businesses.</p>
<p>ComplaintsBBB.com seeks to promote healthy, constructive communication between consumers and businesses. We do our best to try to achieve this goal. We make no guarantees. If anyone has any ideas about how ComplaintsBBB.com might do this better, we would appreciate hearing from you at our e-mail address info@ComplaintsBBB.com.</p>
<p>The messages posted to ComplaintsBBB.com are only the opinions of consumers and businesses and other site users. The complaints do not represent the opinions of ComplaintsBBB.com.</p>
<p>ComplaintsBBB.com will notify users (by sending an e-mail) of account status changes. This includes account modification and account deletion.</p>
<p>ComplaintsBBB.com is only a platform for consumers to file complaints; ComplaintsBBB.com does not lookup or provide e-mail addresses for the subject businesses.</p>
<p>ComplaintsBBB.com is not responsible for helping consumers resolve their complaints. Complaints is only a tool that consumers can use to try to help themselves.</p>
<p>ComplaintsBBB.com may or may not help users resolve complaints posted to the ComplaintsBBB.com site and/or forwarded to the subject businesses.</p>
<p>ComplaintsBBB.com in not responsible, in any way, for providing or helping to provide businesses’ responses to the consumer complaints posted the ComplaintsBBB.com site.</p>
<p>When a message is posted to ComplaintsBBB.com, the Web page and consumer message is indexed by search engines, which are not related to ComplaintsBBB.com. When a page is indexed, it is added to search engine’s index and can be located via a search query using that particular search engine.</p>
<p>When an entire posted complaint is deleted from ComplaintsBBB.com (either at the instruction of a U.S. court or the author of that message, the original message writer) any search index that previously indexed that complaint still maintains that complaint in its search engine document and link cache, despite that complaint already having been deleted from ComplaintsBBB.com.</p>
<p>ComplaintsBBB.com will not attempt to remove or update outdated links to deleted messages or references by third-party search engines, directories or Web sites to content on ComplaintsBBB.com.</p>
<p>By submitting a complaint, you grant the owner of this site, Sagacity Corporation, the irrevocable, transferable, worldwide right to use, reproduce, and display any such information for any purpose commercial or otherwise without compensation to any party.</p>
<p>MEMBER CONDUCT</p>
<p>As a condition of your use of the Service, you warrant to ComplaintsBBB.com that you will not use the Service for any purpose that is unlawful or prohibited by these terms, conditions, and notices.</p>
<p>The Service is provided to individuals only and for personal use only. You agree to use the Service only to post (send) and view (receive) personal messages. Any unauthorized commercial use of the Service, or the resale of its services, is expressly prohibited.</p>
<p>You agree to abide by all applicable local, state, national and international laws and regulations and are solely responsible for all acts or omissions that occur under your account or password, including the content of your transmissions through the Service. By way of example, and not as a limitation, you agree not to:</p>
<p>Use the Service in connection with surveys, contests, pyramid schemes, chain letters, junk e-mail, spamming or any duplicative or unsolicited messages (commercial or otherwise).<br />
  Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others. Publish, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, racist, indecent or unlawful material or information. Advertise or offer to sell or buy any goods or services for any non-personal purpose. Harvest or otherwise collect information about others, including e-mail addresses, without their consent. Create a false identity for the purpose of misleading others as to the identity of the sender or the origin of a message.<br />
  Use, download or otherwise copy, or provide (whether or not for a fee) to a person or entity that is not a Service member any directory of the Service members or other user or usage information or any portion thereof other than in the context of your use of the Service as permitted under the TOS.<br />
  Transmit or upload any material that contains viruses, Trojan horses, worms, time bombs, cancel bots, or any other harmful or deleterious programs.<br />
  Transmit or upload any material that contains software or other material protected by intellectual property laws, rights of privacy or publicity or any other applicable law unless you own or control the rights thereto or have received all necessary consents.<br />
  Interfere with or disrupt networks connected to the Service or violate the regulations, policies or procedures of such networks.<br />
  Attempt to gain unauthorized access to the Service, other accounts, computer systems or networks connected to the Service, through password mining or any other means.<br />
  Violate any applicable laws or regulations including, without limitation, laws regarding the transmission of technical data or software exported from the United States through the service.<br />
  Interfere with another member’s use and enjoyment of the Service or another individual’s or entity’s use and enjoyment of similar services.</p>
<p>ComplaintsBBB.com has no obligation to monitor the Service or any user’s use thereof or retain the content of any user session. However, ComplaintsBBB.com reserves the right at all times to monitor, review, retain and/or disclose any information as necessary to satisfy any applicable law, regulation, legal process or governmental request.</p>
<p>LINKS TO THIRD PARTY SITES</p>
<p>THE LINKS INCLUDED WITHIN THE SERVICE MAY LET YOU LEAVE THE SERVICE WEB SITES (“LINKED SITES”). THE LINKED SITES ARE NOT UNDER THE CONTROL OF ComplaintsBBB.com AND ComplaintsBBB.com IS NOT RESPONSIBLE FOR THE CONTENTS OF ANY LINKED SITE OR ANY LINK CONTAINED IN A LINKED SITE, OR ANY CHANGES OR UPDATES TO SUCH SITES. ComplaintsBBB.com IS NOT RESPONSIBLE FOR WEBCASTING OR ANY OTHER FORM OF TRANSMISSION RECEIVED FROM ANY LINKED SITE. ComplaintsBBB.com IS PROVIDING THESE LINKS</p>
<p>TO YOU ONLY AS A CONVENIENCE, AND THE INCLUSION OF ANY LINK DOES NOT IMPLY ENDORSEMENT BY ComplaintsBBB.com OF THE SITE OR ANY ASSOCIATION WITH THEIR OPERATORS.</p>
<p>DISCLAIMERS/LIMITATION OF LIABILITY</p>
<p>The information and services included in or available through the Service may include inaccuracies or typographical errors. Changes are periodically added to the information herein. ComplaintsBBB.com and/or its respective suppliers may make improvements and/or changes in the Service at any time.</p>
<p>ComplaintsBBB.com does not represent or warrant that the Service will be uninterrupted or error-free, that defects will be corrected, or that the Service or the server that makes it available, are free of viruses or other harmful components.</p>
<p>ComplaintsBBB.com does not warrant or represent that the use or the results of the use of the Service or the materials made available, as part of the Service will be correct, accurate, timely, or otherwise reliable. You specifically agree that ComplaintsBBB.com shall not be responsible for unauthorized access to or alteration of your transmissions or data, any material or data sent or received or not sent or received, or any transactions entered into through the Service.</p>
<p>You specifically agree that ComplaintsBBB.com is not responsible or liable for any threatening, defamatory, obscene, racist, offensive or illegal content or conduct of any other party or any infringement of another’s rights, including intellectual property rights. You specifically agree that ComplaintsBBB.com is not responsible for any content sent using and/or included in the Service by any third party.</p>
<p>ComplaintsBBB.com is not responsible for helping consumers resolve their complaints. Complaints is only a tool that consumers can use to try to help themselves. ComplaintsBBB.com may or may not help users resolve complaints posted to the ComplaintsBBB.com site and/or forwarded to the subject businesses.</p>
<p>ComplaintsBBB.com AND/OR ITS RESPECTIVE SUPPLIERS MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY, RELIABILITY, AVAILABILITY, TIMELINESS, AND ACCURACY OF THE SERVICE FOR ANY PURPOSE. THE SERVICE IS PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND. ComplaintsBBB.com AND/OR ITS RESPECTIVE SUPPLIERS HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH REGARD TO THE SERVICE, INCLUDING ALL IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT.</p>
<p>IN NO EVENT SHALL ComplaintsBBB.com AND/OR ITS SUPPLIERS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF USE, DATA OR PROFITS, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OR PERFORMANCE OF THE SERVICE OR RELATED WEB SITES, WITH THE DELAY OR INABILITY TO USE THE SERVICE OR RELATED WEB SITES, THE PROVISION OF OR FAILURE TO PROVIDE SERVICES, OR FOR ANY INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS OBTAINED THROUGH THE SERVICE, OR OTHERWISE ARISING OUT OF THE USE OF THE SERVICE, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, EVEN IF ComplaintsBBB.com OR ANY OF ITS SUPPLIERS HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. BECAUSE SOME STATES/JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SERVICE, OR WITH ANY OF THESE TERMS OF USE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SERVICE AND ITS RELATED WEB SITES.</p>
<p>INDEMNIFICATION</p>
<p>You agree to indemnify and hold ComplaintsBBB.com, its parents, subsidiaries, affiliates, officers and employees, harmless from any claim, demand, or damage, including reasonable attorneys’ fees, asserted by any third party due to or arising out of your use of or conduct on the Service.</p>
<p>TERMINATION</p>
<p>ComplaintsBBB.com may terminate your access to any part or all of the Service and any related service(s) at any time, with or without cause, with or without notice, effective immediately, for any reason whatsoever.</p>
<p>ComplaintsBBB.com may also terminate your account for inactivity, which is defined as failing to log into the Service for an extended period of time, as determined by ComplaintsBBB.com. The amount of time that ComplaintsBBB.com currently views as an “extended” period of time is 90 days since your last log-on. Upon termination of the Service, your right to use the Service immediately ceases.</p>
<p>If you wish to terminate your account, your only recourse is to discontinue the use of the Service.</p>
<p>ComplaintsBBB.com shall have no obligation to maintain any content in your account or to forward any unread or unsent messages to you or any third party.</p>
<p>NO SPAM; DAMAGES</p>
<p>ComplaintsBBB.com will immediately terminate any account, which it believes, in its sole discretion, is transmitting or is otherwise connected with any Spam or other unsolicited bulk e-mail. In addition, because damages are often difficult to quantify, if actual damages cannot be reasonably calculated then you agree to pay ComplaintsBBB.com liquidated damages of $5 for each piece of Spam or unsolicited bulk e-mail transmitted from or otherwise connected with your account, otherwise you agree to pay ComplaintsBBB.com’s actual damages, to the extent such actual damages can be reasonably calculated.</p>
<p>PARTICIPATION IN PROMOTIONS OF ADVERTISERS</p>
<p>Any dealings with Advertisers on the Service or participation in promotions, including the delivery of and the payment for goods and services, and any other terms, conditions, warranties or representations associated with such dealings or promotions, are solely between you and the Advertiser or other third party. ComplaintsBBB.com shall not be responsible or liable for any part of any such dealings or promotions.</p>
<p>PROPRIETARY RIGHTS TO CONTENT</p>
<p>You acknowledge that content, including but not limited to text, software, music, sound, photographs, video, graphics or other material contained in either sponsor advertisements or electronically distributed, commercially produced information presented to you by the Service, by ComplaintsBBB.com, or ComplaintsBBB.com’s Advertisers or other content providers, is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. All user content (all information submitted to the ComplaintsBBB.com site from users) is owned by Sagacity Corporation, including, but not limited to, messages, images and files. You may view online or make a copy of this content for your personal, noncommercial use only, provided that you keep all copyright and other proprietary notices intact. You may not modify, copy, reproduce, republish, upload, post, transmit, or distribute in any way content available through the Service and its associated Web sites, including code and software.</p>
<p>MODIFICATIONS TO TERMS OF SERVICE, MEMBER POLICIES</p>
<p>ComplaintsBBB.com reserves the right to change the TOS or policies regarding the use of the Service at any time and to notify you by posting an updated version of the TOS on this Web site. You are responsible for regularly reviewing the TOS. Continued use of the Service after any such changes shall constitute your consent to such changes.</p>
<p>GENERAL</p>
<p>The laws of the State of Washington, and the United States of America govern this agreement. Use of the Service is unauthorized in any jurisdiction that does not give effect to all provisions of these terms and conditions, including without limitation this paragraph. You agree that no joint venture, partnership, employment, or agency relationship exists between you and ComplaintsBBB.com as a result of this agreement or use of the Service. ComplaintsBBB.com’s performance of this agreement is subject to existing laws and legal process, and nothing contained in this agreement is in derogation of ComplaintsBBB.com’s right to comply with governmental, court and law enforcement requests or requirements relating to your use of the Service or information provided to or gathered by ComplaintsBBB.com with respect to such use. If any part of this agreement is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the agreement shall continue in effect. Unless otherwise specified herein, this agreement constitutes the entire agreement between the user and ComplaintsBBB.com with respect to the Service (excluding the use of any software which may be subject to an end-user license agreement) and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between the user and ComplaintsBBB.com with respect to the Service. A printed version of this agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. You and ComplaintsBBB.com agree that any cause of action arising out of or related to this Service must commence within one (1) year after the cause of action arose; otherwise, such cause of action is permanently barred. The section titles in the TOS are solely used for the convenience of the parties and have no legal or contractual significance.</p>
<p>COPYRIGHT AND TRADEMARK NOTICES</p>
<p>All contents of the Service are: Copyright (c) 2008, 2009, 2010 GEMS  and/or its suppliers, c/o ComplaintsBBB.com, P.O. BOX 352 SEATTLE, WA 98106</p>
<p>TRADEMARKS.</p>
<p>ComplaintsBBB.com products and services referenced herein are either trademarks or registered trademarks of ComplaintsBBB.com (division of Gems Corporation). The names of actual companies and products mentioned herein may be the trademarks of their respective owners.</p>
<p>The example companies, organizations, products, people and events depicted herein are fictitious. No association with any real company, organization, product, person, or event is intended or should be inferred. Any rights not expressly granted herein are reserved.</p>
</div>
<div class='body' id='margin' style='width:45px; float: left;'>&nbsp;
</div>
<div class='body' id='runninglist' style="width: 360px; float:left">
<h3 class='subhead'>Unsatisfied with a business dealing?</h3>
</div>
<?php include_once('footer.inc'); ?>
